JNU-Parking-Ticket-Project/Parking-Ticket-BE

- Ticket-Api/src/main/java/com/jnu/ticketapi/config/HttpContentCacheFilter.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/config/ServletFilterConfig.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebForwardedHeaderConfig.java
- ContentCache 기능과 X-Forwarded-XXX header를 처리하기 위한 세팅입니다.
- ForwardedHeader 의 Bean을 주입시켜주는 레이어를 Application에서 별도의 Config를 만들어서 주입을 해주었습니다.
지금의 Bean 생성방식이 좋아 보이지는 않아서 나중에 Web 별도의 Configuration을 설계하면 그 곳으로 migration하겠습니다.
- 부가 설명 : ForwardedHeader는 사용자 ip를 servlet에 전달받기 위해서 추가하는 겁니다.
https://hwan-shell.tistory.com/381 를 참고해보시길 바랍니다.
closes
- closed #9
> [BE-5] feat: HttpContentCache처리 #9

- Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
- /v1/auth/login 요청을 post뿐만 아니라 다른 HttpMethod도 filter 안거치게 수정
closes
> [BE-27] : hotfix: SecurityConfig 수정

- Ticket-Domain/src/main/resources/application-domain.yml
[Hotfix] refactor: 배포 서버의 hibernate ddl-auto을 임시로 create-drop 으로 설정
> [Hotfix] refactor: 배포 서버의 hibernate ddl-auto을 임시로 create-drop 으로 설정

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/controller/CaptchaController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/model/response/CaptchaPendingResponse.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaPendingUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaPendingUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaPendingAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/Captcha.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/CaptchaPending.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/CaptchaErrorCode.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/NotFoundCaptchaException.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/NotFoundCaptchaPendingException.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/WrongCaptchaAnswerException.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaLoadPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaPendingLoadPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaPendingRecordPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaPendingRepository.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaRepository.java
- Ticket-Domain/src/main/resources/application-domain.yml
- 캡챠 도메인 추가
- 클라이언트가 캡차를 로드하는 API 추가
- 캡챠를 검증하는 ValidateCaptchaUseCase 추가
- 클라이언트가 캡차를 로드할 때 마다, CAPTCHA_PENDING 테이블에 기록됩니다. 캡챠를 사용할 주차권 신청 동안 최대한 서버의 부하를 줄이기 위해, 캡챠가 검증되어도 CAPTCHA_PENDING에서 데이터를 지우지는 않고 isPending을 false로 변경합니다.
- @pyg410  @LJH098  주차권 신청 도메인 서비스에서 갭챠 검증 로직 추가해주세요. 비즈니스 코드 내부에서 사용할 것이라고 생각해서 따로 API 만들지 않고 UseCase만 만들었습니다.
- 캡챠 이미지와 디비 정보는 이미 S3와 production DB에 저장했습니다.
- 캡챠 이미지 손실 방시를 위해, ddl-auto도 update로 변경합니다.
- 티켓 번호 (27)이 겹치네요. 이슈 확인하고 티켓 번호 사용해주세요~
closes #62
> [BE-27] 캡차 기능 추가

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/controller/CaptchaController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/model/response/CaptchaPendingResponse.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaPendingUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaPendingUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/controller/CouncilController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/model/request/SignUpCouncilRequest.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/model/response/SignUpCouncilResponse.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/service/CouncilUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
- Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ResponseMessage.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaPendingAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/Captcha.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/CaptchaPending.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/CaptchaErrorCode.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/NotFoundCaptchaException.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/NotFoundCaptchaPendingException.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/WrongCaptchaAnswerException.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaLoadPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaPendingLoadPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaPendingRecordPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaPendingRepository.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaRepository.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/adaptor/CouncilAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/domain/Council.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/out/CouncilLoadPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/out/CouncilRecordPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/repository/CouncilRepository.java
학생회 회원가입
학생회 로그인과 마친가지로
일반 사용자(user)와 학생회(council)은 서로 다른 성질을 지닌 act이고 같은 도메인으로 볼 수 없을 것 같아서 domain쪽도 분리하고 UseCase, Adaptor 도 분리하였습니다.
domain쪽에는 User domain과 중복되는 코드가 있을 겁니다 ex) Port, Adaptor..
코드는 중복되긴 하지만 명확한 책임분리와 유연성이 증가한다는 장점때문에 분리하게 되었습니다.
closes #68 
- [#68]
> [BE-32] feat: 학생회 회원가입

- Ticket-Api/build.gradle
build.gradle 단에서 env값을 추가해서 AWS SES env 값들이 배포서버에서 적용되지 않는 버그를 해결
마이너한 핫픽스이므로 리뷰없이 바로 머지합니다
closes
> [Hotfix] AWS SES env 값들이 배포서버에서 적용되지 않는 버그를 해결

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/controller/CaptchaController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/model/response/CaptchaPendingResponse.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaPendingUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaPendingUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/controller/RegistrationController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/response/GetCaptchaResponse.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Encryption.java
- Ticket-Api/src/main/resources/application.yml
- Ticket-Common/src/main/java/com/jnu/ticketcommon/dto/SuccessResponse.java
- Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/DecryptionErrorException.java
- Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/EncryptionErrorException.java
- Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/Captcha.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/CaptchaPending.java
캡챠 pk를 FE한테 그대로 보내주지 않고 AES 알고리즘을 통해 인코딩을 해서 보내준다. (captchaCode 보내줌)
1차 신청에서 인코딩된 캡쳐 코드를 받아 복호화해서 정답이 맞는지 검사
application.yml 환경변수 처리한거는 노션 env 파일에다가 올려놓음
closes #83
> [BE-40] bug : 임시저장 / 1차신청

- Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/EnumClass.java
- Ticket-Common/src/main/java/com/jnu/ticketcommon/deserializer/CustomEnumDeserializer.java
- 기존 Enum을 JacksonMessageConverter를 통해 역직렬화를 통해 사용했는데 이때문에 EnumValidator AOP가 걸리지 않았습니다.
때문에  별도로 Deserializer를 걸어서 적용시켰습니다.
```java
@Override
public Enum<?> deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException {
final JsonNode jsonNode = jp.getCodec().readTree(jp);
final String text = jsonNode.asText();
final Class<? extends Enum> enumType = (Class<? extends Enum>) this._valueClass;
if (enumType == null) return null;
return Arrays.stream(enumType.getEnumConstants())
.filter(value -> value.name().equals(text))
.findAny()
.orElse(null);
}
```
json 을 Text로 변환시켜  name에 value와 일치시키는지 검증하여 deserializer를 걸어주니 IllegalArgumentException이 발생하지 않아 정상 흐름으로 동작합니다.
closes
- closed #128
> [BE-61] feat: CustomEnumDeserializer #128

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/controller/AuthController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/service/AuthUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/common/aop/EmailMethodArgumentResolver.java
- Ticket-Common/src/main/java/com/jnu/ticketcommon/consts/TicketStatic.java
- access, refresh의 principal을 비교하여 같으면 재발급 하는 로직에서 토큰의 claim에있는 email을 비교하여 같으면 재발급 되도록 로직 수정
토큰 재발급 테스트 코드를 짜고있었던 중이라 바로 머지하겠습니다.
테스트 코드를 짜던 중 잘 안되서 디버그 찍다가 발견한 오류인데 ... 다시한번 테스트 코드의 중요성을 깨닫고 갑니다.. ㅜㅜ
closes #132 
- [#132]
> [BE-63] bug: 토큰 재발급

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaRepository.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationLoadPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java
- Data JPA를 이용하여 isSaved가 true, isDeleted가 false인 것만 조회되도록 수정
- CaptchaRepository의 findOneByOffset에 @param 추가
@Kwon770 CaptchaRepository의 findOneByOffset에 @Param 안붙여주니 에러가 떠서 붙여줬습니다. 배포환경에서 왜 잘 되는지 잘 모르겠지만 혹시몰라서 붙여두겠습니다.
closes #145 
- [#145]
> [BE-68] bug : 1차 신청 목록 조회

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/handler/RegistrationCreationEventHandler.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/event/RegistrationCreationEvent.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/User.java
기존 모든 로직을 FP스럽게 Result로 변경했습니다.
기존 구간별 event 재고 감소 로직에 전체 재고를 함꼐 줄일 수 있게 개선했습니다.
재고 감소에 따라 사용자의 상태가 합격인지 불합격인지 예비번호인지 추가하는 기능을 추가했습니다.
- 예비 번호 검증은 추 후 Issueing 처리하겠습니다.
- 기존 모든 로직의 처리를 Event 기반으로 분리해서 로직 분리 했습니다.
- 이렇게 분기처리를 fold 로 처리하는 로직은 어때보이시나요?
closes
- closed #144
> [BE-67] feat: 학생 상태(합격자, 예비자...) 변경 #144

- Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
- AUTHENTICATION_NOT_VALID reason 변경
closes #166 
- [#166]
> [BE-81] style: 엑세스 토큰이 비어있는 경우 예외 메세지 수정

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/event/RegistrationCreationEvent.java
- NPE 픽스
- 메일링 신청 상태 전송 버그 픽스
- 겸사겸사 Registration에 데이터 플로우와 맞지 않는 로직으로 인해 NPE발생하는 부분 픽스했구, 
- 메일링 이벤트를 유저 상태 변경 이벤트 발행 후에 진행되도록 로직 수정했습니다.
closes #163
> [BE-78] bug: 메일 전송시 신청 합격 상태가 전부 불합격으로 전송되는 버그 픽스

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/CheckEmailExceptionDocs.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/CouncilLoginExceptionDocs.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/UserLoginExceptionDocs.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/docs/CouncilSignUpExceptionDocs.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventWithDrawUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/docs/FinalSaveExceptionDocs.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/docs/TemporarySaveExceptionFDocs.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/aop/redissonLock/RedissonLock.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/aop/redissonLock/RedissonLockAop.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/NotOpenEventStatusException.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/event/RegistrationCreationEvent.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/exception/RegistrationErrorCode.java
+ Redisson parameterize
기존 validation을 open ready 상태에서 모두 검증할 수 있도록 추가했습니다.
redisson 분산락 유일하게 적용하는 부분에 userId parameter로 추가된 관계로 분산락 로직을 전부 변경했습니다.
identifier기반으로 변경했습니다.
closes
- closed #175
> [BE-85] feat: event timePeriod Validation off -> on

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/model/response/SectorReadResponse.java
- 구간 인원 설정의 구간 정원, 예비 정원을 초기 설정한 값을 불러오도록 수정
- 서현이가 바쁜 관계로 제가 대신 간단하게 수정 하였습니다.
closes
> [BE-87] bug: 구간 인원 설정

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventRegisterUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Event.java
FP style migration
start = 과거, end = 과거 시간으로 수정할 수 있게 처리했습니다.
(단, 과거, 과거 시간으로 생성하는 것은 불가능합니다.)
기존 모든 분기 처리를 Vavr Option을 이용해서 if문을 제거하려 했으나, 내부 람다 처리 내에서 Option분기 처리를 하면 depth처리가 너무 힘들었습니다. 케이스가 4가지 이상으로 많아진다면 Case 를 처리하겠습니다.
FP를 적용하게 되면 공통 로직을 처리하기 위해서 currid함수를 이용해야 하겠지만 고정 변수가 있지 않다 보니 자유롭게 분기 처리하기는 어려운 부분이 있습니다. 
closes
- closed #187
> [BE-89] feat : Event TimePeriod 과거/과거 시간 수정 허용

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/request/EventRegisterRequest.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventRegisterUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/controller/SectorController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/docs/ReadSectorExceptionDocs.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/model/response/SectorReadResponse.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorReadUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorRegisterUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/EventAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/SectorAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Event.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/EventLoadPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/SectorLoadPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/EventRepository.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/SectorRepository.java
- 이벤트별 섹터 조회
- 최근 이벤트에 연결된 섹터 조회(READY,OPEN 이벤트이거나, CLOSED밖에 없다면 그중 가장 가까운 Event 제시)
- Event 에 title 칼럼을 추가합니다. ( Event별로 Sector를 관리합니다. )
closes
- closed #189
> [BE-90] feat : Event Identifier migration / 이벤트별 섹터 조회 및 섹터 수정 #189

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/controller/SectorController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/docs/UpdateSectorExceptionDocs.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorRegisterUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/SectorAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/InvalidSizeSectorException.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/SectorErrorCode.java
기존 병렬 수정 연산에 Name으로 유니크 검사하는 것을 sectorNum으로 변경했습니다.
또한 2개의 배열을 싱크를 맞추는 과정에서 IntStream으로 인덱스를 맞춰주었습니다.
- closes #221
> [BE-106] bug: sectorNum 구간 이름 중복 검증 로직 수정 #221

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/UpdatePublishStatusUseCase.java
- Ticket-Api/src/test/java/com/jnu/ticketapi/events/UpdatePublishStatusTest.java
- Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ResponseMessage.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Event.java
- 통합테스트
- feat: 이벤트의 PUBLISH 상태 변경 API 
closes #235
> [BE-113] feat: 이벤트의 PUBLISH 상태 변경 API

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/docs/CreateEventExceptionDocs.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventRegisterUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorDeleteUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorRegisterUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/EventAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/SectorAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Event.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/PublishStatusTrueException.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/EventLoadPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/SectorLoadPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/SectorRepository.java
- spotless
- 이벤트 PUBLISH가 TRUE인 경우 구간/시간 설정 불가능하게 변경
- EXCEPTION 추가
- 생각보다 서현이 코드를 손댈 일이 거의 없더라구요(다행)
- 추가적으로 수정해야할 부분이 있을까요?
closes #238
> [BE-114] feat: 이벤트 PUBLISH 상태에 따라 시간/구간 설정 변경가능하게 로직 수정

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/docs/DeleteEventExceptionDocs.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventDeleteUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventRegisterUseCase.java
- Ticket-Api/src/main/resources/db/teardown.sql
- Ticket-Api/src/test/java/com/jnu/ticketapi/events/DeleteEventTest.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Event.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/User.java
1. Entity Casecade 수정
1-1. Sector를 삭제 시 해당 구간에 관련된 Registration을 삭제한다.
1-2. User를 삭제 시 해당 User가 신청한 Registration을 삭제한다.
위 와 같은 의도로 
```java
//Registration Entity
@OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE)
@JoinColumn(name = "user_id")
private User user;
@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE)
@JoinColumn(name = "sectorId", nullable = false)
private Sector sector;
``` 
이렇게 한 것 같은데 Registration(부모) : Sector(자식) = N : 1 -> cascade는 Remove는 부모가 삭제되면 자식도 삭제된다.
따라서 1-1의 의도와는 정반대(신청 삭제 시 구간 삭제가 되버림)가 되버려서 데이터베이스 무결성 오류가 뜬다.
그래서 양방향 매핑으로 mappedBy로 부모 정하고 Casecade All 적용해줌.
2. Event 삭제 (소프트 딜리트)
3. Event 삭제 통합 테스트
4. Event 삭제 예외 docs
5. DB Event Table에 직접 is_deleted Column 추가
2, 3, 4번은 간단한거라 자세한 설명은 건너 뛰었습니다.
closes #243 
- [#243]
> [BE-117] feat : 이벤트 삭제

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/response/EventsInfoResponse.java
- 응답에 이벤트의 publish 상태 정보 추가
코드 한줄 수정한거라 바로 merge 하겠습니다.
closes #250 
- [#250]
> [BE-119] feat : 이벤트 목록 조회

- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/SectorAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/SectorRepository.java
```java
public List<Sector> findAllByEventStatusAndPublishAndIsDeleted() {
List<Sector> sectors = couponRepository.findAllByEventStatus();
return sectors.stream()
.filter(sector -> sector.getEvent().getPublish() && !sector.getEvent().isDeleted())
.toList();
}
``` 
이벤트 상태가 OPEN 이거나 READY인 것을 가져와서 서비스 레이어에서 filter링 하는 것으로 바꿧다.
closes #261 
- [#261]
> [BE-124] fix : 구간 목록 조회

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/docs/CreateSectorExceptionDocs.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorDeleteUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/SectorAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/SectorLoadPort.java
구간을 삭제 할 때 클라이언트에게 보여지는 에러를 세분화 할 필요가 있어보여서 에러케이스를 세분화 하였습니다.
ex) 이벤트가 publish되서 구간 추가, 수정,삭제가 안되는건데 에러 문구는 `존재하지 않은 구간입니다` 라는 문구가 떠서 클라이언트를 혼란스럽게 한다.
closes #263 
- [#263]
> [BE-125] refactor: 구간 삭제 에러케이스 세분화

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/docs/CreateEventExceptionDocs.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/docs/UpdateEventExceptionDocs.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventRegisterUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventUpdateUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/vo/DateTimePeriod.java
```java
public static void validateEventIssuePeriod(DateTimePeriod dateTimePeriod) {
LocalDateTime nowTime = LocalDateTime.now();
if (dateTimePeriod.getEndAt().isBefore(nowTime)
|| dateTimePeriod.getStartAt().isBefore(nowTime)
|| dateTimePeriod.getEndAt().isBefore(dateTimePeriod.getStartAt())) {
throw InvalidPeriodEventException.EXCEPTION;
}
}
``` 
DateTimePeriod에 static 메서드로 이벤트 발급 가능 시간을 검증하는 메서드를 추가하였습니다.
이 static메서드로 EventRegisterUseCase, EventUpdateUseCase에서 검증을 하였습니다.
closes #267 
- [#267]
> [BE-127] feat:이벤트 시간 설정, 수정 validate

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventDeleteUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/controller/SectorController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorDeleteUseCase.java
- Ticket-Batch/src/main/java/com/jnu/ticketbatch/EventDeletedEventHandler.java
- Ticket-Batch/src/main/java/com/jnu/ticketbatch/expired/BatchQuartzJob.java
- Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventRegisterJob.java
- Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventUpdateJob.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/SectorAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Event.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/SectorRecordPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/SectorRepository.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationRecordPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/redis/RedisRepository.java
1. 이벤트 삭제시 이벤트의 status를 CLOSED로 바꾸고 is_deleted를 true로 update한다.
2. 이벤트 삭제, 이벤트의 시간이 다 지나서 CLOSED시 redis 비우고 관련 sector, registration 삭제
3. Sector Entity에 isDeleted 추가
- DB에 직접 컬럼 추가 완료
4. Quartz withIdentity에서 eventId 제거
5. 구간 삭제 시 구간과 연관된 신청(registration)을 모두 소프트 딜리트
6. reFinalRegisterProcess에서 isSaved를 true로 업데이트 하도록 수정
1. EventDeletedEventHandler에서 `@SneakyThrows`를 사용했던데 이T 어노테이션은 checked exception을 마치 unchecked exception처럼 취급하게 해주는 어노테이션인 걸로 알고있다. 
`@SneakyThrows`를 메소드에 적용하고 던질 주체 없이 throw 만 하고있던데 이게 가능한건지? 아니면 잘못 작성한건지 궁금하다. (일단 저는 컴파일 에러가 떳습니다.)
2. 이벤트 삭제 시 redis를 비워야하는데 redis에 정확히 무엇을 어떻게 저장하고있는지 파악하지 못하여 `REDIS_EVENT_ISSUE_STORE` 를 Key로 가지는 것을 지우는 것으로 했는데 옳바르게 한 것인지?
3. reFinalRegisterProcess은 finalSave 작업이므로 isSaved를 true로 변경하는게 맞지 않나?
closes #274 
- [#274
> [BE-131] feat: 이벤트 상태가 CLOSED 될 시 redis 비우고 관련 sector, registration 삭제

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventWithDrawUseCase.java
```java
@RedissonLock(
LockName = "주차권_발급",
identifier = "userId",
waitTime = 5000,
leaseTime = 10000,
timeUnit = TimeUnit.MILLISECONDS)
``` 
leasetime을 지금 3초로 처리하고 있는데 이메일이 길어지면 분산락이 풀리면서 에러가 터진다. 따라서 leaseTime을 3초 -> 10초로 변경
closes #278 
- [#278]
> [fix] : RedissonLock waitTime, leaseTime

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
```java
public void decreaseEventStock() {
checkEventLeft();
if (isSectorCapacityRemaining()) {
decreaseCapacity();
} else if (isSectorReserveRemaining()) {
decreaseReserve();
} else {
throw NoEventStockLeftException.EXCEPTION;
}
}
``` 
remain_amount를 checkEventLeft에서도 if에서도 검사하고 있어서 Capacity가 남았는지 검사하도록 수정
closes #280 
- [#280]
> [BE-134] bug: sector의 reserve가 감소하지 않는 오류

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationRecordPort.java
Registration을 저장하는 코드 save -> saveAndFlush로 변경
ProcessEventData는 EventIssuedEventHandler에 위치되어있으며 비동기로 메인로직과 분리되어있다.
```java
private void processEventData(Long userId) {
Registration registration = registrationAdaptor.findByUserId(userId);
Sector sector = registration.getSector();
User user = registration.getUser();
if (sector.isSectorCapacityRemaining()) {
user.success();
} else if (sector.isSectorReserveRemaining()) {
Long waitingOrder =
waitingQueueService.getWaitingOrder(REDIS_EVENT_ISSUE_STORE, userId);
user.prepare(Integer.valueOf(waitingOrder.intValue()));
} else {
user.fail();
}
Events.raise(RegistrationCreationEvent.of(registration, user.getStatus()));
sector.decreaseEventStock();
}
``` 
따라서 메인로직 (Registration을 save) 보다 processEventData가 먼저 실행되면 …
> [BE-135] bug: processEvent에서 registration이 null이뜨는 오류

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/handler/RegistrationCreationEventHandler.java
- Ticket-Api/src/test/java/com/jnu/ticketapi/mailService/MailServiceTest.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/event/RegistrationCreationEvent.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/MailService.java
- 신청 메일 전송시 기존 "예비"로 보내지던 기능을 "예비 n번"으로 보내지게끔 기능 추가 했습니다.
외부 API와 연동하는 부분이다 보니, 테스트가 외부 API와 의존하게 됩니다. 흑흑
지금 SES 문제 없는지 궁금하네요
로컬환경에서 테스트시 SES 부분이 샌드박스로 변경된 거 같은데, 확인 부탁드려용
세부 로그는 슬랙 `프로젝트 토의` 채널에 올렸습니다.
closes #284
> [BE-136] feat: 합불 메일 전송시 예비번호 상태 추가 

- Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/vo/DateTimePeriod.java
DateTimePeriod format변경
이벤트 생성요청의 DateTimePeriod가 format이 일치하지 않아 에러가 났다.
closes #315
> [BE-151] fix: DateTimePeriod format 변경

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/UpdatePublishStatusUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/EventAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/EventLoadPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/CustomEventRepository.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/CustomEventRepositoryImpl.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/EventRepository.java
- publish된 이벤트가 있는지 확인 하는 쿼리를 QeuyDsl로 수정하였습니다.
- 임시저장된 것은 EventIssuedEventHandler에서 isSaved만 true로 바꾸고 저장하는 것으로 수정하였습니다.
closes #320
> [BE-153] bug: 임시저장하고 최종신청하면 신청이 두번 되는 오류

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/vo/DateTimePeriod.java
```java
private void validateEventStatusIsClosed(Event event) {
if (event.getEventStatus().equals(EventStatus.CLOSED) ||
event.getDateTimePeriod().isAfterEndAt(LocalDateTime.now())) {
throw AlreadyCloseStatusException.EXCEPTION;
}
}
``` 
1. 단순히 event의 상태가 CLOSED인지만 확인하는 것이 아닌 현재 시간과 endAt을 비교하도록 수정하였습니다.
- 그 이유는 만약 OPEN 상태에서 CI/CD로 인한 재배포가 될경우 CLOSED 스케줄링이 적용이 안되는 현상을 발견함. (즉, 시간이 지나도 CLOSED로 바뀌지 않음)
2. 기존 validate 메서드 parameter로 sector -> event
- sector에서 event를 꺼내서 사용하던 것을 수정
closes #333
> [BE-161] : Termporary, finalSave에서 유효성 검증 추가

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventWithDrawUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/EventAdaptor.java
1. EventPeriod의 조회할 때 현재시간이 event endAt보다 이후 일때 예외 보내기
2. /events/period를 SecurityFilter에서 제외
closes #335
> [BE-162] feat: Event의 Period 조회

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
이벤트가 closed인지 확인하는 부분과 시간을 검증하는 부분을 분리하여습니다.
closes
> [fix] : bug: 이벤트 시작전이면 신청폼으로 안들어가지는 버그

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/EventAdaptor.java
```java
return event.filter(
e ->
e.getPublish()
e.getPublish()
&& !e.getDateTimePeriod().isAfterEndAt(LocalDateTime.now()))
.map(Result::success)
.orElseGet(() -> Result.failure(NotFoundEventException.EXCEPTION));
``` 
게시되지 않은 이벤트가 아닌 게시된 이벤트를 filter함
closes #339
> [fix] : bug: event Period 조회 에러

- Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventRegisterJob.java
t2.micro 기준 ProcessQueueDataJob 실행 주기 1초(1000ms)로 테스트 했을 때  #348 같은 문제가 발생.
실제 prod 환경에서는 t3.2xlarge 이기 때문에 실행 주기를 200ms로 변경
실행주기를 판단하는 기준
1. TaskExecutor Thread Pool
- ProcessQueueDataJob에서 publish 하는 event를 listen하는 곳이 EventIssedEventHandler 인데 이것은 @Async로 되어있어 AsyncConfig에 정의한 TaskExecutor Thread Pool에서 관리가 된다.
2. WorkerThread
- 스케줄러에 등록된 job을 workerThread에서 수행되기 때문에 이또한 실행 주기에 밀접한 관련이 있다고 판단하였다.
3. CPU 및 메모리
- 병렬 처리 향상과 컨택스트 스위칭 최소화는 CPU와 밀접한 관계가 있다고 판단 하였고, ec2의 메모리는 Redis 환경과 관계가 있다고 판단
CPU 및 메모리 이외에 TaskExecutor Thread Pool 갯수나 Batch, Scheduler Worker Thread pool 갯수 설정은 변함이 없다. 
CPU가 8배 차이가 남으로 1000ms / 8 = 125ms... 그러나 너무 짧은 주기는 오버헤드를 증가 시킬 수 있기에 일단 200ms로 수정 후 prod환경에서 테스트를 진행해보려고 한다.
- 출처 : https://aws.amazon.com/ko/ec2/instance-types/
closes #348
> [BE-169] refactor: ProcessQueueDataJob 실행 주기 변경

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventDeleteUseCase.java
- Ticket-Batch/src/main/java/com/jnu/ticketbatch/expired/BatchQuartzJob.java
주차권 신청 redis 대기열(zset) key가 "쿠폰 발급 저장소" 하나만 사용하기 때문에 deleteKeysByPrefix -> delete 로 수정
closes #354
> [BE-172] bug: 이벤트 삭제 시 redis 데이터 삭제되지 않는 현상

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
- Ticket-Batch/src/main/java/com/jnu/ticketbatch/config/ProcessQueueDataJob.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/event/RegistrationCreationEvent.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationRecordPort.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/domainEvent/EventIssuedEvent.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/WaitingQueueService.java
> redis 대기열 가장 앞에 있는 데이터로 EventIssuedEvent를 publish -> Handler에서 EventIssuedEvent에 있는 Registration을 저장 -> 이메일 전송 -> redis에서 해당 데이터 pop 
위와 같은 방식으로 코드를 수정
예전에 코드를 이렇게 짜고 테스트를 했었는데 redis에서 pop이 되지 않아 계속 같은 신청 데이터만 저장이 되어서 코드를 다르게 짯었는데 
그때는 ProcessQueueDataJob 주기를 5 seconds로 적용해서 병목 현상 때문에 안된 것 같습니다... 200ms 로 바꾸니 잘 되네요
칩 : Apple M1 pro
메모리 : 16GB
OS : macOs Sonma 14.6.1
- [1구간, 20, 40, 60]
- [2구간, 30, 30, 60]
- [3구간, 20, 40, 60]
- [4구간, 5, 55, 60]
- [5구간, 10, 50, 60]
총 290 개의 신청 요청이 날라감.
총 282개의 신청이 저장 되었음.
총 구간 재고(300) - 총 신청 수 (282) = 남은 재고 수 (18) 이 예상됨.
2구간 (7) + 4구간(11) = 18
예상과 정확히 맞아 떨어짐
“쿠폰 발급 저장소”의 key가 안보임으로 정상적으로 redis 대기열에서 모든 신청 데이터가 pop 되었음을 알 수 있음.
**총 신청(290) - 총 신청 저장 수(282) = 8개는  k6 테스트 할 때 구간을 랜덤하게 신청을 보내는데  재고가 다 찬 곳에 신청을 넣으려고 하고 있는 것**
칩 : Apple M1 pro
메모리 : 16GB
OS : …
> [BE-175] bug: redis 대기열에서 데이터를 pop 하고 db에 저장하지 못하는 문제

- Ticket-Api/build.gradle
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/TestUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/handler/RegistrationCreationEventHandler.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/slack/sender/SlackInternalErrorSender.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/handler/UserReflectStatusEventHandler.java
- Ticket-Batch/src/main/java/com/jnu/ticketbatch/config/ProcessQueueDataJob.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/event/RegistrationCreationEvent.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/event/RegistrationPublishEvent.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationLoadPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/User.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/UserStatus.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/UserStatusConverter.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/event/UserReflectStatusEvent.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/redis/RedisRepository.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/WaitingQueueService.java
1. [ProcessQueueDataJob 최적화](https://github.com/JNU-Parking-Ticket-Project/Parking-Ticket-BE/commit/5796ef95a0b1e60f012985143af150451ae273dd) 
- value와 socre를 따로 조회하는 것이 아닌 한번에 조회하기
2. [Sector에 DynamicUpdate 추가](https://github.com/JNU-Parking-Ticket-Project/Parking-Ticket-BE/commit/9ef7a81080100abe857e449ba315b81b8f9ba1cb) 
- 재고 감소가 빠르게 될 수 있도록 더티체킹 시 변동이 있는 필드에만 update
3. [reflectUserStatus 분리](https://github.com/JNU-Parking-Ticket-Project/Parking-Ticket-BE/commit/11b0a2143cc0e2ec066a9063b29fe74b8f488476) 
-  user의 상태 체크는 다른 트랜잭션으로 분리 (구간별로 저장된 신청이 몇번째로 들어왔는지로 합격 여부 판별)
4. [UserStatus 도입 및 신청서 조회 로직 수정](https://github.com/JNU-Parking-Ticket-Project/Parking-Ticket-BE/commit/83e03c124e627125d3be582852d62fce696cd60a) 
- 신청서 조회 할 때 합격자가 예비자보다 먼저 오도록 하기위해 UserRole(Enum을 도입하면 더 쉽게 관리 할 수 있음)을 …
> Refactor #177

- Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebLoggingInterceptor.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebProperties.java
- Ticket-Api/src/main/resources/application.yml
```
M3M4 2024-09-05 00:03:20.705  INFO --- [nio-8080-exec-1] c.j.t.config.WebLoggingInterceptor       : Method: POST, URL: /api/v1/auth/check/email, User: anonymous, ResponseType: application/json, ResponseTime: 158ms
```
```
oO7mzD 2024-09-05 00:05:19.095  INFO --- [nio-8080-exec-5] c.j.t.config.WebLoggingInterceptor       : Method: POST, URL: /api/v1/registration/1, User: 7, ResponseType: application/json, ResponseTime: 81ms
oO7mzD 2024-09-05 00:05:19.096  INFO --- [nio-8080-exec-5] c.j.t.config.WebLoggingInterceptor       : [registration request] {
"name": "홍길동",
"studentNum": "183027",
"affiliation": "공과대학",
"carNum": "12가1234",
"isLight": true,
"phoneNum": "010-1111-3333",
"selectSectorId": 1,
"captchaCode": "1234",
"captchaAnswer": "1234"
}
```
closes #370
> [BE-370] 비유저가 호출할 수 있는 요청 로깅 시 anonymous로 유저 정보 남기도록 변경

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/controller/AuthController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/service/AuthUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventDeleteUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventWithDrawUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventRegisterJob.java
- Ticket-Common/build.gradle
- Ticket-Domain/src/main/resources/application-domain.yml
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedisConfig.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedissonConfig.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/redissonLock/RedissonLockAop.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/redis/RedisRepository.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/redis/RedisService.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/WaitingQueueService.java
- @ConditionOnExpression으로 ableRedis가 false일 때 redis 관련된 것 Bean 등록 안되게 수정
- Common pools 2 의존성 추가
- redis health check on/off 환경변수화
> @Kwon770 redis가 꺼져있을 때는 .env에서 ABLE_REDIS=false, ABLE_REDISSON=false 으로 실행시켜주시고 redis가 정상적으로 켜졌을 때는 ABLE_REDIS=true, ABLE_REDISSON=true 로 실행시켜주세요
1. ableRedis와 ableRedisson을 false로 하고 redis를 실행시키지 않았을 때 Commons pool2 에러가 떠서 의존성을 추가해주었습니다.
2. redis health check를 제외시키지 않았을 때 redis가 연결되지 않았다고 에러가 떠서 redis가 켜지지 않았을 때는 health check에서 제외시켰습니다.
1. ableRedis와 ableRedission을 false로 하고 redis를 실행시키지 않았을 때 정상적으로 springBoot가 실행되는 모습
2. 로그인 정상적으로 성공
3. 임시저장 정상적으로 성공
> @Kwon770 redis가 꺼져있을 때는 .env에서 ABLE_REDIS=false, ABLE_REDISSON=false 으로 실행시켜주시고 redis가 정상적으로 켜졌을 때는 ABLE_REDIS=true, ABLE_REDISSON=true 로 실행시켜주세요
closes #378
> [BE-183] feat: 레디스 없이도 서버 정상 가동

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventDeleteUseCase.java
ableRedis가 false일 때 redis 대기열을 삭제하지 않도록 수정
closes #384
> [BE-186] bug: 이벤트 삭제가 되지 않는 오류

- Ticket-Common/build.gradle
- commons-pool2 의존성 제거
- [#379] 에서 commons-pool2를 빼고 ABLE_REDIS, ABLE_REDISSON을 false로 시작하면 lettuceFactory에러가 떳었는데 이번에 commons-pool2를 빼니 정상작동함... 아마 lettuce:pool:enabled를 true로 하고 있었어서 그런 것 같음
closes #397
> [BE-192] bug: Commons-pool2 의존성 제거

- Ticket-Api/src/main/java/com/jnu/ticketapi/ConfigurationApiPropertiesConfig.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/application/HashResult.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Encryption.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/config/EncryptionProperties.java
- Ticket-Api/src/main/resources/application.yml
- Ticket-Api/src/test/java/com/jnu/ticketapi/WithCustomMockUser.java
- Ticket-Api/src/test/java/com/jnu/ticketapi/WithCustomUserContextFactory.java
- Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaUseCaseTest.java
- Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaUseCaseTest.java
- Ticket-Api/src/test/java/com/jnu/ticketapi/application/helper/EncryptionTest.java
- Ticket-Api/src/test/java/com/jnu/ticketapi/registration/FinalSaveTest.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaLogAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/CaptchaLog.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/CaptchaErrorCode.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/WrongCaptchaCodeException.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaLogPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaLogRepository.java
- Ticket-Domain/src/test/java/com/jnu/ticketdomain/domains/captcha/CaptchaLogRepositoryTest.java
A. 솔트 생성
- SecureRandom을 사용하여 16바이트 길이의 솔트 값 생성
- 매 요청마다 랜덤으로 값 생성
B. 데이터 준비
1) 캡차 ID(Long)를 문자열로 변환 후 UTF-8 바이트 배열로 변환
cf) 해시 함수 사용을 위해 바이트 배열로 변환 과정이 필요함 
2) 솔트(16바이트)와 데이터 바이트를 하나의 배열로 결합
cf) combineSaltAndData 함수에서 확인 가능
```java
private byte[] combineSaltAndData(byte[] salt, byte[] data) {
// 전체 바이트 배열 생성 (솔트 길이 + 데이터 길이)
byte[] combined = new byte[salt.length + data.length];
// 1. 먼저 솔트를 복사 (인덱스 0부터 16바이트)
System.arraycopy(salt, 0, combined, 0, salt.length);
// 2. 그 다음에 데이터를 복사 (인덱스 16부터 N바이트)
System.arraycopy(data, 0, combined, salt.length, data.length);
return combined;
}
```
C. 해시값 생성
- 결합된 바이트 배열에 대해 SHA-256 해시 수행
D. 결과 반환
- salt와 해시값(captchaCode)를 인코딩하여 해당 값을 HashResult 객체에 담음
1. SHA-256 알고리즘 특징
- SHA-256은 단방향 해시 알고리즘
- 해시값 → 원본 데이터로 변경은 불가능
- 단, 동일한 입력값에 대해 항상 동일한 해시값 생성
2. 이러한 …
> [BE-195] bug: 캡차 암호화 일정한 문제 해결

- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/repository/AnnounceImageNativeRepository.java
1. INSERT_IGNORE 쿼리 수정
- 테이블 명의 대소문자를 구별하도록 설정되어 있는 것 같아서 실제 DB에 있는 테이블 명으로 수정함
closes #426
> [BE-203] bug: 공지사항 수정 오류 해결

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/handler/UserReflectStatusEventHandler.java
- Ticket-Api/src/test/java/com/jnu/ticketapi/registration/GetRegistrationsTest.java
- Ticket-Batch/src/main/java/com/jnu/ticketbatch/config/ProcessQueueDataJob.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationLoadPort.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/model/ChatMessage.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/model/ChatMessageStatus.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/redis/RedisRepository.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/WaitingQueueService.java
1. reRegisterQueue 제거
- ChatMessage에서 ChatMessageStatus를 제거 했기 때문에 reRegisterQueue를 제거
- ProcessQueueDataJob에서 publish 한 ChatMessage가 Waiting이면 EventIssuedEventHandler가 처리중인 것으로 보고
EventIssuedEventHandler는 Not_Watiting인 것 만 처리 하도록 ChatMessageStatus 도입했지만 
지금은 그냥 Waiting/Not_Waiting 상관없이 가장 앞에껄 가져와서 처리하기 때문에 ChatMessageStatus 삭제
2. Registration Entity에 saved_at 도입
- LocalDateTime이 아닌 Long 타입
- finalSave를 할 때 현재 시간을 나노 단위 정수로 변환하여 저장
3. FinalSave 할 때 RegistrationUseCase 에서 update(dirty-checking) 하는 것 제거
- DB에 저장하는 EventIssuedEvent에서 update / insert 하도록 수정
4. 합격/불합격 기준 (UserReflectStatusEventHandler)
- 기존 : PK 순으로 정렬 후 몇 번 째 데이터인지 확인 
- 수정 후 : saved_at 으로 정렬 후 몇 번 째 행 데이터인지 확인
approve 받고 머지 할 때 dev, prod DB에 saved_at 컬럼 추가하도록 하겠습니다
closes #399
> [BE-193] bug: 합격/예비/불합격 기준 수정 

- Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/cache/CacheTestConfiguration.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/domain/AnnounceImage.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/repository/AnnounceImageNativeRepository.java
- Ticket-Domain/src/test/java/com/jnu/ticketdomain/AnnounceImage/repository/AnnounceImageNativeRepositoryTest.java
- 공지사항 수정시 created_at null로 들어가는 bug Fix
- isDeleted 컬럼 매핑 타입 변경(tinyint -> bit)
- 테스트 수정
수정완료
closes #428
> [BE-204] bug: 공지사항 수정시 created_at null입력 오류

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/UpdateAnnounceUseCase.java
1. UpdateAnnounceUseCase.execute에서 @CachePut을 CacheEvict로 수정
- @CachePut은 공지사항 수정 할 때 캐시를 무효화 하는 것이 아니라 수정하는 거라서 UpdateAnnounceResponse를 캐싱하게 됨  이러면 공지사항 상세조회를 할 때 AnnounceDetailsResponse가 응답으로 가야하는데 캐싱된 UpdateAnnounceResponse가 반환되려고 하여 반환타입 불일치
- 따라서 캐시 강제 무효화시키는 @CacheEvict로 수정
- #434 에 나온 에러 로그 참고
@pyg410 으악 버그다!
closes #434
> [BE-208] bug: 공지사항 오류

- initdb/init.sql
- `docker-compose.yml`에서 사용하는 `initdb/init.sql` 스크립트를 최신화했습니다.
- `ticket` 데이터베이스 `drop (if exists)`, `create`, `use` 명령어를 포함합니다.
closes #452
> [BE-215] chore: DB 초기화 스크립트 최신화

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/FixedCaptchaHashProcessor.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/RandomCaptchaHashProcessor.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebConfig.java
- Ticket-Api/src/main/resources/application.yml
- Ticket-Api/src/main/resources/db/teardown.sql
- Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/FixedCaptchaHashProcessorTest.java
- Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaUseCaseTest.java
- Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/RandomCaptchaHashProcessorTest.java
- Ticket-Api/src/test/java/com/jnu/ticketapi/registration/FinalSaveTest.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaLogAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/FixedCaptchaAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/RandomCaptchaAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaRepository.java
- Ticket-Domain/src/test/java/com/jnu/ticketdomain/domains/captcha/CaptchaRepositoryTest.java
- 부하 테스트를 위한 `fixed` 환경에서 captcha 요청 및 답변 검증이 가능하도록 구현했습니다.
- 신청을 위해 `captcha` 이미지 조회 시 DB에 저장된 첫번째 captcha 데이터가 조회됩니다.
- 개발서버 도메인을 CORS에 추가했습니다.
- 테스트 환경의 `encryption.salt-type`이 `fixed`로 변경되었습니다.
closes #457 
- 테스트 케이스가 추가되었습니다.
- `fixed` 환경에서 사용하는 `hashProcessor`의 코드 검증 실패 케이스
- `fixed` 환경에서 사용할 첫번째 캡챠 조회 쿼리
> [BE-218] feat: fixed 환경에서 captcha 요청 및 답변 검증이 가능하도록 구현

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/controller/CouncilController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/docs/CouncilSendEmailException.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/handler/EmailSendEventHandler.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/service/CouncilUseCase.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/TestUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/exception/CouncilErrorCode.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/exception/SendFailEmailException.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/event/SendEmailEvent.java
CouncilController에 POST요청 API 만든 후, CouncilUseCase에서 이벤트 객체 발행하였습니다.
이메일 전송 실패시 에러 메시지 뜰 수 있게 ErrorException 구현하였고, 기존에 EventExpiredEventHandler코드를 재사용하나, 이름을 EmailSendEventHandler로 만들어 코드의 사용 의도를 명확히 하였습니다.
다만, 아직 테스트코드 작성이 안 된 상태입니다.
EventExpiredEventHandler, EventExpiredEvent, EventExpiredEventRaiseGateway, BatchConfiguration을 참조하여 기능을 구현하려 했습니다. 이 때, eventId가 메일 발송 이벤트에 사용되는 것 같다고 판단했습니다. 그래서 현재 프론트에서 path variable로 받아온 eventId로 EmailSendEventHandler를 실행하는데, 이 방법이 유효한지 의문입니다.
#456 
closes
> [BE-217] feat: 이메일 전송 기능 구현

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/controller/CouncilController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/model/response/SendEmailManuallyResponse.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/service/CouncilUseCase.java
- Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ResponseMessage.java
```json
{
"message": "메일 전송에 성공하셨습니다."
}
```
위와 같은 방식으로 응답 값을 반환하는 기능을 구현했습니다.
</br>
현재 ResponseMessage에서 이메일 전송 성공과 실패 메시지를 모두 관리하고 있는데,
따로 Exception으로 빼야할까요?(CouncilErrorCode처럼 따로 관리를 해야하는지 묻고싶습니다!)
closes #463
> [BE-221] feat: feat: 이메일 수동으로 보내는 api 에서 응답 값 설정 

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
- 1차 신청시 캡챠 검증 로직이 중복신청 검증 로직보다 앞에 있도록 수정
- 뭐가 없긴합니다..
closes : #465
> [BE-222] fix: 캡챠 답변 응답 메시지 수정

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
- Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/service/CredentialCodeUseCase.java
- Ticket-Api/src/main/resources/application.yml
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
- Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/MailService.java
- 이메일 환경변수가 `dev`, `prod`에만 적용되어 로컬, 테스트 환경에서 실행 및 테스트가 깨지는 문제 발생
- `profile`을 구분하지 않고 해당 속성을 통일해 관리하도록 변경
- `Sector`의 `Registration`에 대한 양방향 연관관계 리스트에 `final` 키워드 적용
closes #470
> [BE-224] bug: 이메일 주소 환경변수에 의한 로컬 실행 및 테스트 에러 수정

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/service/CouncilUseCase.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/StillOpenEventException.java
현재 주차권 이벤트가 `CLOSED `상태가 아님에도 수동으로 메일 전송 버튼을 눌렀을 때, 전송을 성공했습니다.
이를 주차권 이벤트가 `CLOSED `상태에만 수동으로 이메일 전송 요청을 보낼 수 있게 수정했습니다.
`CLOSED `상태가 아닐경우 에러를 던지게 끔 수정했습니다.
`eventId`에 해당하는 `EventStatus`가 `CLOSED`일 때만 요청이 가게끔 코드를 수정하려했습니다.
이를 위해 `eventId`로 해당 `EventStatus`를 가져오려 했는데, 이 때 `eventAdaptor`에 `findById`를 사용했습니다.
이 방법이 유효한지 확인부탁드립니다.
closes #474
> [BE-226] bug: 주차권 이벤트가 끝나지 않았을 때 이메일 전송 api 요청이 성공하는 오류

- Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java
- 예비 번호 중복 문제 버그 해결
- 최종 신청 후 saved_at을 애플리케이션이 아닌 DB가 설정하는 방식으로 수정
- native query 이용하여 mysql의 UNIX_TIMESTAMP 함수 사용
- 컨펌해주세요
closes #227
- 예비 번호 중복 할당 문제를 임시로 해결하는 방안으로 순서보장은 되지 않으며 빠른 시일내에 수정 필요
> [BE-227] bug : 예비 번호 중복 문제 버그 임시 해결

- Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
- initdb/init.sql
- Registration 테이블의 유니크 제약조건에 email 컬럼을 추가 했습니다 #496 
- init sql에 누락된 ddl을 추가했습니다 #500 
closes #496, #500
> [BE-234] bug: Registration 테이블 유니크 키 제약조건 사이드 이펙터 제거
