JNU-Parking-Ticket-Project/Parking-Ticket-BE

Ticket-Api/src/main/java/com/jnu/ticketapi/config/ExampleHolder.java
Ticket-Api/src/main/java/com/jnu/ticketapi/config/SwaggerConfig.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/ApiErrorCodeExample.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/ApiErrorExceptionsExample.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/consts/TicketStatic.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/BadLockIdentifierException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/ExpiredTokenException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/InvalidPasswordException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/InvalidTokenException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/NotAvailableRedissonLockException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerBadRequestException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerExpiredTokenException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerForbiddenException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerInternalSeverErrorException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerNotFoundException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerUnauthorizedException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OutOfIndexException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/RefreshTokenExpiredException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/SecurityContextNotFoundException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/TicketCodeException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/TicketDynamicException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/XssScriptAttackException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/interfaces/SwaggerExampleExceptions.java

- Custom 으로 Annotation기반으로 Reflect로 Example을 생성하여 모든 문서에 반영하게 했습니다.
- Tag :  제목
- Exception Response Example 자동 문서 생성
- Error Response Example 자동 문서 생성
- Basic Auth 로 Swagger Login 을 추가할 예정 ( AccessDenied 추가 처리 예정 )
closes
- closed #11

[BE-6] feat: Swagger Custom 설정

---

Ticket-Api/src/main/java/com/jnu/ticketapi/adapter/in/SystemController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/application/port/ScheduleUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/application/service/ScheduleService.java
Ticket-Api/src/main/java/com/jnu/ticketapi/dto/ScheduleRequestDto.java
Ticket-Api/src/main/java/com/jnu/ticketapi/dto/ScheduleResponseDto.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/Port.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domain/system/System.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domain/system/SystemRepository.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/out/SystemLoadPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/out/SystemRecordPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/persistence/SystemPersistenceAdapter.java

- 시작/종료 설정 기능에 필요한 Structure 구현
시작/종료 설정 기능 Structure 빼고 삭제했습니다.
기존 기능 구현 코드의 명복을 빌어주세요...
closes #18

[BE-10] [feat] : 시작/종료 설정 기능Structure

---

.github/workflows/CI_Check.yml

- spotless 체크
- sonar cloud 적용 및 analyze workflows를 작성했습니다.
closes
- closed #33

[BE-19] feat: CI_Check #33

---

Ticket-Api/src/main/java/com/jnu/ticketapi/TicketApiApplication.java
Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebConfig.java

- Mvc CORS설정을 Application이 아닌 WebMvcConfugurer를 상속받은 WebConfig에 작성
- SecurityConfig에 corsConfiurationSource 작성
closes

[BE-27] hotfix: CORS 설정

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/controller/AnnounceController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/request/SaveAnnounceRequest.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/request/UpdateAnnounceRequest.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnounceDetailsResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnounceInfoResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnouncePagingResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnounceResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/DeleteAnnounceResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/SaveAnnounceResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/UpdateAnnounceResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/DeleteAnnounceUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/GetAnnouncesUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/SaveAnnounceUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/UpdateAnnounceUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/DeleteAnnounceTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/GetAnnouncesTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/SaveAnnounceTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/UpdateAnnounceTest.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/AnnounceIdNotExistException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/AnnounceNotExistException.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/adaptor/AnnounceAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/domain/Announce.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/out/AnnounceLoadPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/out/AnnounceRecordPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/repository/AnnounceRepository.java

[BE-27] hotfix: 빌드 안되는 것 수정

---

Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java

- Security debug true로 수정
closes

[BE-27] hotfix : SecurityConfig 수정

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/controller/AnnounceController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/docs/DeleteAnnounceExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/docs/GetAnnounceExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/docs/UpdateAnnounceExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/controller/NoticeController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/docs/GetNoticeExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/model/request/UpdateNoticeRequest.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/model/response/NoticeResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/model/response/UpdateNoticeResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/service/GetNoticeUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/service/UpdateNoticeUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/config/DatabaseCleaner.java
Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/config/DatabaseClearExtension.java
Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/GetAnnouncesTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/notice/integration/GetNoticeTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/notice/integration/UpdateNoticeTest.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/NoticeNotExistException.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/adaptor/AnnounceAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/notice/adaptor/NoticeAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/notice/domain/Notice.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/notice/out/NoticeLoadPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/notice/out/NoticeRecordPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/notice/repository/NoticeRepository.java

- 공지사항 Swagger 예외 추가
- spotless 적용
- 안내사항 Swagger 예외 추가
spotless적용했습니당
예외처리도 Swagger에 문서화 추가했습니당
closes #63

[BE-29] docs: 공지사항, 안내사항 기능 Swagger 예외 추가 

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/controller/UserController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/model/request/FindPasswordRequest.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/model/request/UpdatePasswordRequest.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/model/response/FindPasswordResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/model/response/UpdatePasswordResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/service/CredentialCodeUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/service/UpdatePasswordUseCase.java
Ticket-Api/src/main/resources/templates/findPassword.html
Ticket-Api/src/test/java/com/jnu/ticketapi/user/FindPasswordTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/user/UpdatePasswordTest.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/consts/MailTemplate.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/message/MailMessage.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/CredentialCode/adaptor/CredentialCodeAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/CredentialCode/domain/CredentialCode.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/CredentialCode/out/CredentialCodeLoadPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/CredentialCode/out/CredentialCodeRecordPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/CredentialCode/repository/CredentialCodeRepository.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/adaptor/UserAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/User.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/exception/CredentialCodeNotExistException.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/exception/UserErrorCode.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/out/UserRecordPort.java
Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/thymeleaf/ThymeleafConfig.java
Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/MailService.java

- 비밀번호 인증 링크 메일 전송 기능
- 비밀번호 재설정 기능
- spotless적용
- integration test 작성
일단 AWS SES에 제 메일 추가해서 하긴 했는데, 이 부분은 추후 학생회 메일로 수정해야할 것 같아요
closes #64

[BE-30] feat: 비밀번호 찾기 기능 

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/controller/CaptchaController.java

누락되었던 캡챠 요청을 위한 Swagger 설명을 추가했습니다.
너무 마이너해서 리뷰 없이 머지합니다!

[BE-27] 캡챠 요청에 대한 Swagger 설명 추가

---

Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/CredentialCode/adaptor/CredentialCodeAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/CredentialCode/repository/CredentialCodeRepository.java

- insert & delete를 한 트랜잭션에 묶었을 때 순서에 상관 없이 insert가 먼저 나가는 규칙이 존재해, 로직을 수정했습니다.
closes #90

[BE-43] bug: 비밀번호 재발급 500 오류 트랜잭션 버그 픽스

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/controller/AdminController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/model/response/GetUsersResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/service/AdminUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/controller/CaptchaController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/controller/RegistrationController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/internal/RegistrationDto.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/response/GetRegistrationsResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationLoadPort.java

신청 목록 조회입니다.
아무 신청이 없을 때에는 List안이 비어있게 됩니다.
closes #92

[BE-44] feat: 1차 신청 목록 조회

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/service/AuthUseCase.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/exception/CouncilErrorCode.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/exception/IsNotCouncilException.java

- 학생회 로그인 할 때 권한 예외처리 추가(학생회, 관리자 권한 아니면 로그인 안됌)
간단한 작업이라 바로 머지합니다
closes #81

[BE-39] bug: 학생회 로그인

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/controller/CouponController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/controller/SectorController.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/dto/SuccessResponse.java

[BE - docs] SuccessResponse 긴급수정

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/controller/UserController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/docs/UpdatePasswordExceptionDocs.java

- 비밀번호 재설정 예외사항 스웨거 적용시켰습니당
closes #110

[BE-51] feat: 예외케이스 Swagger 적용

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/controller/AdminController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/docs/UpdateRoleExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/controller/AuthController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/CheckEmailExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/CouncilLoginExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/TokenReissueExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/UserLoginExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/request/LoginUserRequest.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/service/AuthUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/controller/CaptchaController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/docs/GetCaptchaExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/controller/CouncilController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/docs/CouncilSignUpExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/controller/RegistrationController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/docs/FinalSaveExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/docs/TemporarySaveExceptionFDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/docs/UpdatePasswordExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Encryption.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/NotEqualPrincipalException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/NotFoundRefreshTokenException.java

- AuthController ExceptionDocs 작성
- CouncilController ExceptionDocs 작성
- RegistrationController ExceptionDocs 작성
- CaptchaController ExceptionDocs 작성
단순히 예외 docs 작성이라 바로 머지합니다!~
closes #105 
- [#105]

[BE-48] docs: ErrorDocs 작성

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/service/AuthUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/controller/RegistrationController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/TemporarySaveRequest.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/docs/UpdatePasswordExceptionDocs.java
Ticket-Api/src/test/java/com/jnu/ticketapi/user/LoginTest.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/Phone.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/validator/PhoneValidator.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/util/PhoneNumberInstance.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/vo/PhoneNumberVo.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/adaptor/UserAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/User.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/exception/EmptyPhoneNumException.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/exception/UserErrorCode.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/exception/UserPhoneNumberInvalidException.java
build.gradle

```
01(?:0|1|[6-9])-(?:\d{3}|\d{4})-\d{4}$
```
regex 정규표현식 기준 010-1111-1111 형식으로 검증을 추가했습니다.
또한 Schema 어노테이션으로 swagger에서 확인할 수 있게 설명을 추가해보았습니다.
- Phone
closes
- closed #112

[BE-52] feat: PhoneValidate #112

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/model/response/UpdateRoleResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/service/AdminUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnounceDetailsResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnounceInfoResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnouncePagingResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnounceResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/SaveAnnounceResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/UpdateAnnounceResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/GetAnnouncesUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/SaveAnnounceUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/UpdateAnnounceUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/model/response/NoticeResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/model/response/UpdateNoticeResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/service/GetNoticeUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/service/UpdateNoticeUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/response/FinalSaveResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/response/TemporarySaveResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/model/response/UpdatePasswordResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/service/UpdatePasswordUseCase.java
Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/domainEvent/CouponIssuedEvent.java
Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/CouponSubscribeService.java

- 리팩토링했습니당
- 변경 기준
- of 메서드 : 0~n개의 인자를 받아 해당 클래스를 생성한다.
- from 메서드 : 타 클래스를 통해 해당 클래스를 생성한다.(컨버터 포함)
closes #108

[BE-50] refactor: 부적절한 of, from 메서드 네이밍 변경

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/docs/ReadEventPeriodExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventWithDrawUseCase.java
Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/DeleteAnnounceTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/SaveAnnounceTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/UpdateAnnounceTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/notice/integration/GetNoticeTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/user/UpdatePasswordTest.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/EnumClass.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/NotReadyEventStatusException.java

Open Status -> Read Status
- FP스럽게 변경했습니다.
- 기존 Open Status 를 Read Status 로 변경했습니다.
closes
- closed #130

[BE-62] feat: EventPeriod Get 상태 OPEN -> READY #130

---

Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/vo/DateTimePeriod.java

time Zone UTC change
closes
- closed #134

[BE-64] feat: Event Time UTC Zone setting #134

---

.github/ISSUE_TEMPLATE/기능구현.md
.github/ISSUE_TEMPLATE/리팩터링.md
.github/ISSUE_TEMPLATE/버그수정.md

배포 DB 스키마 업데이트 이슈가 종종 생기므로, 까먹지 않도록 PR 템플릿의 체크리스트에 해당 내용을 추가했습니다.
슬랙에서도 공지한대로, 엔티티를 수정하면 수정자가 책임지고 업데이트하는 것을 까먹지 않도록 추가했습니다.
closes

[Hotfix] chore: DB 스키마 업데이트 체크리스트 추가

---

Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java

간단한 수정사항이라 빠르게 확인만 부탁드려요
closes #137

[BE-65] feat: 프론트 도메인 CORS 설정 추가

---

Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebConfig.java

- SecurityConfig에 무의미한 cors config code 제거
- Webconfig에 cors 주석 추가
- 배포된 프론트 도메인 cors 허용 추가
@LJH098 작성하신 config 코드 다음과 같이 바꿨습니다. 점검한 핫픽스라 바로 머지하지만, 변경사항 사후에 확인부탁드려요.

[Hotfix] : Cors 설정 핫픽스

---

Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java

- preFlightRequest CORS 허용
배포된 프론트 cors를 위한 핫픽스라 일단 리뷰없이 머지합니다.
closes

[Hotfix] : Cors 설정 핫픽스 2

---

Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebConfig.java

여러 개의 cors url을 리스트로 안넘기고 여러 번 선언해서 제대로 할당되지 않은 휴먼에러 해결...
바보 이슈라 바로 머지...

[Hotfix] : Cors 설정 핫픽스 3

---

Ticket-Api/src/main/java/com/jnu/ticketapi/TicketApiApplication.java
Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebConfig.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/Phone.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/validator/PhoneValidator.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/vo/DateTimePeriod.java

[BE-66] feat: Phone, Password Validator 미작동 이슈 해결 #142

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventWithDrawUseCase.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ResponseMessage.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
build.gradle

- event reset 기능이 추가됐습니다.
- domain 
- init_sector_capacity
- init_reserve 초기 값을 추가했습니다. 그래야 reset을 할 수 있거든요
closes
- closed #152

[BE-71] feat: Event 초기화 #152

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/docs/UpdateRoleExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/service/AdminUseCase.java
Ticket-Api/src/test/java/com/jnu/ticketapi/admin/UpdateRoleTest.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/admin/adaptor/AdminAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/admin/exception/AdminErrorCode.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/admin/exception/AlreadyExistAdminException.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/admin/exception/NotAllowUpdateOwnRoleException.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/admin/out/AdminLoadPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/admin/out/AdminRecordPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/adaptor/UserAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/out/UserLoadPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/repository/UserRepository.java

관리자가 이미 존재하는 경우 관리자로 변경못하게 막음(관리자는 1명만 가능하게)
자기 자신의 권한을 변경 못하게 막음(관리자가 실수로 자신의 권한을 변경할 수 있는걸 방지)
closes #157 
- [#157]

[BE-74] bug : 권한 설정

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/model/request/SignUpCouncilRequest.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ValidationMessage.java

- 비밀번호 불일치 예외 메세지 수정
- 이름 공백 예외 메세지 수정
- 올바르지 않는 전화번호 형식 예외메세지 수정
- 학번 공백 에외 메세지 수정
closes #159 
- [#159]

[BE-75] style : 예외 메세지 수정

---

Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java

- ACCESSTOKEN_NOT_VALID 403 -> 401 수정
closes #166 
- [#166]

[style] : GlobalErrorCode

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/CheckEmailExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/CouncilLoginExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/UserLoginExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/request/ReissueTokenRequest.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/docs/CouncilSignUpExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/docs/FinalSaveExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/docs/TemporarySaveExceptionFDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/TemporarySaveRequest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/auth/ReissueTokenTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/registration/FinalSaveTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/registration/TemporarySaveTest.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ValidationMessage.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/exception/RegistrationErrorCode.java

- Auth Valid 예외 추가
- Admin Valid 예외 추가
- Council Valid 예외 추가
- Registration Valid 예외 추가
closes #161 
- [#161]

[BE-76] docs : Valid 예외 docs

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
Ticket-Domain/src/main/resources/application-domain.yml

검증을 UseCase로 위임했습니다. 재고 검증 절차를 2단계로 분리했습니다.
closes
- closed #171

[BE-82] feat: 중복 최종 신청 방지 리펙토링 #171

---

Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ValidationMessage.java

ValidationMessage 수정
closes #174 
- [#174]

[BE-84] style: ValidationMessage 수정

---

Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java

[BE-84] style : NOT_EVENT_OPEN_STATUS 메세지 수정

---

Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java

- sector의 update 메서드 수정(initReserve와 initSectorCaptacity도 수정하도록 함)
closes #180 
- [#180]

[BE-87] bug : 구간 인원 설정

---

Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java

Reverts JNU-Parking-Ticket-Project/Parking-Ticket-BE#182

Revert "[BE-87] bug : 구간 인원 설정"

---

Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java

Reverts JNU-Parking-Ticket-Project/Parking-Ticket-BE#183

Revert "Revert "[BE-87] bug : 구간 인원 설정""

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/response/EventsInfoResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/response/EventsPagingResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/GetEventsUseCase.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/EventAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/EventLoadPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/EventRepository.java

[feat] : 이벤트 목록 조회 페이지네이션

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/controller/RegistrationController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationLoadPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java

- 해당 event에 대한 신청 목록 조회로 수정
closes #192 
- [#192]

[BE-92] refactor: 신청 목록 조회

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventWithDrawUseCase.java

[BE-93] feat: event별 신청 기한 조회 #193

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java

이벤트컨트롤러 버그 픽스
createdAt -> id
closes

[fix] : 이벤트 목록 조회 페이지네이션 버그 픽스

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/response/EventsInfoResponse.java

spotless적용
이벤트 목록 조회 response 날짜 포맷 변경
closes

[fix] : 이벤트 목록 조회 페이지네이션 날짜 포맷 변경

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/response/EventDetailResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/GetEventDetailUseCase.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/SectorRepository.java

해당 이벤트 상세조회 기능을 작성하였습니다.
응답 
- 구간
- started_at
- ended_at
-  title
- status
closes #199 
- [#199]

[BE-95] feat: 이벤트 상세 조회

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/response/EventDetailResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/GetEventDetailUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorRegisterUseCase.java

[BE-98] feat: sector update all -> current

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/exception/RegistrationErrorCode.java

- 같은 이메일 or 같은 학번을 통해 두번 신청한 경우에 던지는 예외를 잘못 작성해 수정
closes #208 
- [#208]

[BE-99] : 1차 신청

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationLoadPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java

- 같은 이메일 or 같은 학번을 통해 두번 신청한 경우 확인하는 로직에 isSaved 추가
closes #211 
- [#211]

[BE-101] bug: 1차 신청

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/controller/SectorController.java

- 구간 추가하는 부분도 구간 번호가 중복되는지 확인하는 AOP추가
closes

[BE-103] bug: 구간 설정

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/controller/SectorController.java

Reverts JNU-Parking-Ticket-Project/Parking-Ticket-BE#215

Revert "[BE-103] bug: 구간 설정"

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorRegisterUseCase.java

기존 SectorNum이 존재하는지 중복 검사를 실시합니다. 
```java
private Validation<Seq<TicketCodeException>, List<SectorRegisterRequest>>
validateRegistrationSector(
List<SectorRegisterRequest> sectors, List<Sector> prevSector) {
return Validation.combine(
validateUniqueSectorNumbers(sectors),
validatePlusSectorCapacityAndReserve(sectors),
validateDuplicateSectorNum(sectors, prevSector))
.ap(
(uniqueSectorNumbers, plusSectorCapacityAndReserve, duplicatedSector) ->
sectors);
}
```
as-is : 지금은 함수의 validation계층을 combine을 통해 검증을 단계적으로 실시하고 있습니다.
to-be : curried를 써서 함수마다 다른 검증 레이어 구축을 실시할 수도 있겠습니다.
- closes #223

[BE-107] bug: sector post validation ( 기존 등록시 중복 방지 ) #223

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/controller/SectorController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorReadUseCase.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/SectorAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/SectorLoadPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/SectorRepository.java

- 이벤트 상태에 따른 구간 조회로 변경했습니다
closes #225

[BE-108][fix] :이벤트 상태에 따른 구간 조회

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java

[BE-108] [fix] :이벤트 상태에 따른 구간 조회

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/docs/UpdateSectorExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorRegisterUseCase.java
Ticket-Api/src/test/java/resources/application.yml
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/SectorAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/SectorRepository.java
Ticket-Domain/src/test/java/com/jnu/ticketdomain/resources/application-test.yml

- 기존 MultiException을 사용하지 않게 제어흐름을 변경하였습니다.
- 프론트분들에게 각 예외 케이스는 Sector_400_8,9,10 은 전달하겠습니다.
closes
- closes #230

[BE-110] refactor: MultiException -> 단일 예외 롤백 #230

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/response/PublishStatusResponse.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/GetPublishStatusUseCase.java
Ticket-Api/src/test/java/com/jnu/ticketapi/config/BaseIntegrationTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/config/BaseUnitTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/events/GetPublishStatusTest.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Event.java

- 상태조회 API
- 통합테스트코드 작성
- 빠른 리뷰 부탁드림다
closes #234

[BE-112] feat: 이벤트의 PUBLISH 상태 조회 API

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/docs/CreateEventExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/request/EventRegisterRequest.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorRegisterUseCase.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ValidationMessage.java

- 이벤트 생성할 때 제목이 빈칸인지 아닌지 validation 추가 하였습니다.
- 이벤트 생성할 때 날짜를 입력/선택 하였는지 validation 추가 하였습니다.
closes #232 
- [#232]

[BE-111] feat : 이벤트 생성 validation

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
Ticket-Api/src/main/resources/db/teardown.sql
Ticket-Api/src/test/java/com/jnu/ticketapi/admin/GetSignUpCouncilsTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/admin/UpdateRoleTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/registration/FinalSaveTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/registration/GetRegistrationTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/registration/GetRegistrationsTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/registration/TemporarySaveTest.java

테스트 수정
- getSignUpCouncilsTest
- updateRoleTest
- getRegistrationTest
- getRegistrationListTest
- TemporarySaveTest
빌드 돌려서 테스트 통과한 것 확인했습니다.
@pyg410 남은 테스트 수정 해주세용~~
closes #240 
- [#240]

[BE-115] test: 실패한 테스트 수정

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/docs/DeleteEventExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventDeleteUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventRegisterUseCase.java
Ticket-Api/src/main/resources/db/teardown.sql
Ticket-Api/src/test/java/com/jnu/ticketapi/events/DeleteEventTest.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Event.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/User.java

Reverts JNU-Parking-Ticket-Project/Parking-Ticket-BE#245

Revert "Revert "[BE-117] feat : 이벤트 삭제""

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/docs/DeleteEventExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/docs/UpdatePublishStatusExceptionDocs.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/request/UpdateEventPublishRequest.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventDeleteUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventRegisterUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/UpdatePublishStatusUseCase.java
Ticket-Api/src/test/java/com/jnu/ticketapi/events/DeleteEventTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/events/UpdatePublishStatusTest.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/InternalSeverErrorException.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ResponseMessage.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/utils/Result.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/EventAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Event.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/AlreadyExistPublishEventException.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/AlreadyPublishEventException.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/AlreadyUnpublishEventException.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/CannotPublishClosedEventException.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/EventLoadPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/EventRepository.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/User.java

이벤트 publish를 true로 변경하는 것만 가능했었는데 이벤트를 publish, unpublish 할 수 있도록 수정
if 문이 떡칠되어있지만 Validation을 적용해서 리팩토링 더 해보겠습니다.
closes #247 
- [#247]

[BE-118] refactor : 이벤트 PUBLISH 상태 변경

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
Ticket-Api/src/test/java/com/jnu/ticketapi/events/UpdatePublishStatusTest.java

이벤트 publish 상태 변경 예외 docs 추가했습니다.
closes #247

[docs] : 이벤트 publish 상태 변경 예외 docs 추가

---

Ticket-Common/src/main/java/com/jnu/ticketcommon/validator/PasswordValidator.java

```java
public boolean isValid(String value, ConstraintValidatorContext context) {
if (value == null) {
return false;
}
return value.matches("^(?=.*[a-zA-Z])(?=.*\\d)(?=.*[!@#$%^&*])[a-zA-Z\\d!@#$%^&*]{8,16}$");
}
``` 
비밀번호 정규화를 수정하였습니다.
비밀번호에 최소한 하나의 문자(대문자 또는 소문자일 수 있음), 최소한 하나의 숫자, 지정된 세트의 최소한 하나의 특수 문자가 포함되어 있고 총 길이는 8~16자 사이입니다.
closes #265 
- [#265]

[BE-126] feat: 비밀번호 정규화

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventRegisterUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventUpdateUseCase.java
Ticket-Batch/src/main/java/com/jnu/ticketbatch/EventBeforeCreationEventHandler.java
Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventRegisterJob.java
Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventUpdateJob.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/event/EventBeforeCreationEvent.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/event/EventUpdatedEvent.java

- closed #269 
- 기존 변경 로직에 OPEN, CLOSED 자동 처리를 배치로 인가시켰습니다.

[BE-128] Batch Insert update 로직에 추가 반영

---

Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/vo/DateTimePeriod.java

Reverts JNU-Parking-Ticket-Project/Parking-Ticket-BE#316

Revert "[BE-151] fix: DateTimePeriod format 변경"

---

Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java

예외 메세지를 사용자 친화적으로 수정하였습니다.
closes #322

[BE-154] : style 예외 메세지 수정

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/TemporarySaveRequest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/auth/ReissueTokenTest.java
Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ValidationMessage.java

[feat] : 신청할 때 이름 제한 수 두기

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/TemporarySaveRequest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/auth/ReissueTokenTest.java
Ticket-Domain/src/test/java/com/jnu/ticketdomain/DomainIntegrateTestConfig.java

문자열 필드에 @Max Validation을 사용하고 있어서 @Max -> @Size로 변경
closes #331

[BE-160] 신청할 때 이름이 100자 이하여도 오류뜨는 버그

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventWithDrawUseCase.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/EventAdaptor.java

```java
public GetEventPeriodResponse getEventPeriod() {
Result<Event, Object> readyEvent = eventAdaptor.findReadyOrOpenEvent();
return readyEvent.fold(
(event) -> {
if (event.getPublish().equals(false)) throw NotPublishEventException.EXCEPTION;
``` 
findReadyOrOpenAndNotPublishEvent -> findReadyOrOpenEvent
closes #341

[fix] : bug:event period 버그

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/controller/RegistrationController.java
Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventRegisterJob.java
Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedisConfig.java

1. EventRegistrerJob에서 ProcessQueueDataJob의 실행주기를 1초로 수정
2. Swagger에서 의미없는 parameter 안보이게 수정
closes

[BE-167] bug: 쓰레드 블락킹 현상

---

Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventUpdateJob.java

이벤트 삭제 할 때 ProcessQueueDataJob도 삭제되도록 cancelScheduledJob에 ProcessQueueDataJob 삭제하는 것 도 추가하였음
closes #352

[BE-171] feat: 이벤트 삭제 할 때 ProcessQueueDataJob도 삭제

---

Ticket-Batch/src/main/java/com/jnu/ticketbatch/EventCreationEventHandler.java
Ticket-Batch/src/main/java/com/jnu/ticketbatch/EventUpdatedEventHandler.java
Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventRegisterJob.java

ProcessQueueDataJob 실행 시작 시간을 event startAt으로 수정
closes #356

[BE-173] feat : ProcessQueueDataJob 실행 시작 시간을 event startAt으로 수정

---

Ticket-Api/src/main/java/com/jnu/ticketapi/common/actuator/ThreadPoolConfig.java
Ticket-Api/src/main/resources/application.yml

- spring acutator thread pool endpoint 추가했슴다
- 풀 사이즈, 엑티브 스레드 개수, 큐 사이즈, 코어풀 사이즈, 맥스풀 사이즈 넣었습니다.
- /actuator/threadpool 로 요청 날리면 됩니다
closes #350

[BE-170] feat: spring actuator thread pool endpoint 추가의 건

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
Ticket-Batch/src/main/java/com/jnu/ticketbatch/config/ProcessQueueDataJob.java
Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/WaitingQueueService.java

Job이 실행될 때 마다 redis 대기열에 있는 신청 정보를 가져와 모두 event 발행
closes #361

[BE-176] refactor: ProcessQueueDataJob 리팩토링

---

Ticket-Batch/src/main/java/com/jnu/ticketbatch/expired/BatchConfiguration.java
Ticket-Batch/src/main/java/com/jnu/ticketbatch/expired/BatchQuartzJob.java

발송 이벤트 발생을 변경했습니다.
closes
- closed #368

[BE-179] refactor: running trigger condition 변경 #368

---

Ticket-Batch/src/main/java/com/jnu/ticketbatch/expired/BatchConfiguration.java
Ticket-Batch/src/main/java/com/jnu/ticketbatch/expired/BatchQuartzJob.java
Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventRegisterJob.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/EventExpiredEventRaiseGateway.java

[BE-180] refactor: batch expiredEvent Adaptor Gateway throw event #371

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationLoadPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java

임시저장 된 것을 order by desc로 하여 가장 처음걸 가져옴 (가장 마지막에 저장된 걸 가져온 다는뜻)
closes #374

[BE-181] bug: 임시저장 조회 오류 

---

Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventRegisterJob.java
Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventUpdateJob.java

고정된 identity를 사용하는 것이 아니라 eventId를 추가하여 유동적이게 수정
closes #391

[BE-190] bug: 스케줄링 등록 안되는 버그

---

Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventRegisterJob.java
Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventUpdateJob.java

[[fix] : job과 trigger의 identity에 eventId 붙이기](https://github.com/JNU-Parking-Ticket-Project/Parking-Ticket-BE/commit/d5e9e3881039a2ca52b3bf829ff52fec357daae6)
[[fix] : JobKey 생성 하는 부분도 eventId 추가](https://github.com/JNU-Parking-Ticket-Project/Parking-Ticket-BE/commit/0fc89be7663c0561ccc9b067c2ecb5cb21c06000)
closes

[RELEASE] release: V1.1.0

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Encryption.java
Ticket-Domain/src/main/resources/application-domain.yml
Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedisConfig.java

[BE-199] test: 인수 테스트용 PR 

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Encryption.java
Ticket-Domain/src/main/resources/application-domain.yml
Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedisConfig.java

Reverts JNU-Parking-Ticket-Project/Parking-Ticket-BE#410

Revert "[BE-199] test: 인수 테스트용 PR "

---

Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedisConfig.java

[BE-200] bug: redis 트랜잭션 

---

Ticket-Infrastructure/build.gradle

[BE-201] bug: redisson 의존성 삭제

---

Ticket-Api/src/main/java/com/jnu/ticketapi/ConfigurationApiPropertiesConfig.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
Ticket-Api/src/main/java/com/jnu/ticketapi/application/HashResult.java
Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Encryption.java
Ticket-Api/src/main/java/com/jnu/ticketapi/config/EncryptionProperties.java
Ticket-Api/src/main/resources/application.yml
Ticket-Api/src/test/java/com/jnu/ticketapi/WithCustomMockUser.java
Ticket-Api/src/test/java/com/jnu/ticketapi/WithCustomUserContextFactory.java
Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaUseCaseTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaUseCaseTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/application/helper/EncryptionTest.java
Ticket-Api/src/test/java/com/jnu/ticketapi/registration/FinalSaveTest.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaLogAdaptor.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/CaptchaLog.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/CaptchaErrorCode.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/WrongCaptchaCodeException.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaLogPort.java
Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaLogRepository.java
Ticket-Domain/src/test/java/com/jnu/ticketdomain/domains/captcha/CaptchaLogRepositoryTest.java

This reverts commit 44c14345dd934f75145b7337713a4e69adf00ee4.
revert된 커밋을 다시 돌리는 것이므로 바로 merge 합니다.
closes

chore : Revert "Revert "[BE-195] bug: 캡차 암호화 일정한 문제 해결""

---

.github/workflows/build.yaml
.github/workflows/dev-deploy-v2-container.yaml
.github/workflows/dev.yaml

- 테스트를 위해 슬랙 웹훅 주석처리
- workflow-test 브랜치로 코드 push 시 CI 실행

개발서버 배포 테스트용 PR

---

Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebConfig.java

개발 서버 관리자 페이지 URL 에 대해 CORS 허용 설정을 추가했습니다.
closes #454

[BE-216] feat: FE 개발 서버 관리자 페이지 cors 추가

---

Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
Ticket-Api/src/main/java/com/jnu/ticketapi/config/RetryConfig.java
Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/domainEvent/EventIssuedEvent.java
Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/model/ChatMessage.java

- 데드락 문제 임시 해결
- 재시도 기능 활성화 및 추가
closes #508

[BE-242] fix: 데드락 문제 임시 해결
